### ISSUE TITLE
Listen to menu state

### ISSUE THREAD

**Issue by kwado-tech** [chinabrant/popup_menu#2]
Hi, really love your package but there's no available method or functionality to listen to the open and close state of the popup menu in order to dynamically open or close the menu when required? Thanks

**Comment by chinabrant** [comment]
OnDismiss will be called when it is closed.

**Comment by chinabrant** [comment]
For now, just have a onDismiss that will be called when it's closed. I will think about of this, thank you.

**Comment by kwado-tech** [comment]
I can't really determine if the menu state is open or closed and if
menu.dismiss() is called on the menu when it's state is closed, it throws
an error. Thanks

**Comment by chinabrant** [comment]
I have add a stateChanged callback listen to the open ad close state. And a property `isShow`. Pls update pub to 1.0.2.

**Comment by kwado-tech** [comment]
Thanks. I'll check it out
