### ISSUE TITLE
Multiple widgets used the same GlobalKey.

### ISSUE THREAD

**Issue by pkmangukiya** [chinabrant/popup_menu#28]
This error occur when try to  `showPopup` with `ListView.builder`

>       ListView.builder(
>             itemCount: list.length,
>             itemBuilder: (context, index) {
>              return MaterialButton(
>                 key:  btnKey,
>                 child: ListTile(
>                   title: Text("Title"),
>                   subtitle: Text("Title"),
>                   onTap: showPopup,
>                 ),
>                 onPressed: showPopup,
>               );
>             },
>           )

**Comment by AliRn76** [comment]
You cant use GlobalKey Like that , every single widget need a uniq GlobalKey ,
This is my problem to , how can we use that in ListViewBuilder ?

**Comment by AliRn76** [comment]
> This error occur when try to `showPopup` with `ListView.builder`
> 
> > ```
> >   ListView.builder(
> >         itemCount: list.length,
> >         itemBuilder: (context, index) {
> >          return MaterialButton(
> >             key:  btnKey,
> >             child: ListTile(
> >               title: Text("Title"),
> >               subtitle: Text("Title"),
> >               onTap: showPopup,
> >             ),
> >             onPressed: showPopup,
> >           );
> >         },
> >       )
> > ```

You can't use GlobalKey Like that , every single widget has to use a uniqe GlobalKey ,

So you can code something like below, and pass the key to function on tap:
```
ListView.builder(
        itemCount: list.length,
        itemBuilder: (context, index) {
         final GlobalKey btnKey = GlobalKey();
         return MaterialButton(
            key:  btnKey,
            child: ListTile(
              title: Text("Title"),
              subtitle: Text("Title"),
              onTap: showPopup(btnKey),
            ),
            onPressed: showPopup,
          );
        },
      )
```
