### ISSUE TITLE
Close menu on gestures

### ISSUE THREAD

**Issue by kwado-tech** [chinabrant/popup_menu#3]
Thanks a whole lot for your quick responses and dedication to this project. I would suggest an improvement of closing the popup menu if other gestures like swipe/scroll (on page) occurs. This is because the menu only closes if a user taps on the menu item or outside the menu but not other gestures (like scroll through a list the menu still remains open). 
Thanks

**Comment by chinabrant** [comment]
Thanks for you suggestion, i have fix this in version 1.0.3
