### ISSUE TITLE
Can you update this to null safety?

### ISSUE THREAD

**Issue by yusriltakeuchi** [chinabrant/popup_menu#33]
We need this to support null safety please

**Comment by mikah22** [comment]
This is the last package that I use that is not yet updated to Null Safety and is preventing my code from becoming fully null safe. I would really appreciate the author to update their code and help 1000's of users who use this package to move forward.

**Comment by chinabrant** [comment]
2.0.0 support

**Comment by devrajraut** [comment]
v2.0.0 can't be seen on Dart pub.dev
It still shows v 1.0.5 which is not Null Safe. Could You pls have a Look and Push your latest Version to pub.dev

Thanks for this beautiful Package. Cheers!
