### ISSUE TITLE
MenuItem isn't a function Error

### ISSUE THREAD

**Issue by AsadAMalikDeveloper** [chinabrant/popup_menu#40]
![menuItem](https://user-images.githubusercontent.com/58651902/169482189-da36ad2a-43d3-4b41-bf27-e681d1ca94dd.PNG)
![menuItemDe](https://user-images.githubusercontent.com/58651902/169482193-e81b32c9-ed8e-4a29-ba14-aed8b0e64c2a.PNG)

Please Help Me On this... I'm getting this error After upgrading Flutter Sdk

**Comment by zubairehman** [comment]
i am getting the similar error

**Comment by AsadAMalikDeveloper** [comment]
> i am getting the similar error

Downgrade Flutter to 2.10

**Comment by virusHF** [comment]
import 'package:popup_menu/popup_menu.dart' as popMenu;

popMenu.MenuItem
