### ISSUE TITLE
demo caused an exception in dismiss function

### ISSUE THREAD

**Issue by nicorobine** [chinabrant/popup_menu#5]
flutter: menu is showing
flutter: Menu is dismiss
flutter: menu is closed
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 133 pos 12: '_overlay != null':
flutter: is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:133:12)
flutter: #3      PopupMenu.dismiss (package:popup_menu/popup_menu.dart:329:12)
flutter: #4      PopupMenu.buildPopupMenuLayout.<anonymous closure>.<anonymous closure> (package:popup_menu/popup_menu.dart:157:11)
flutter: #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
flutter: #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
flutter: #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)

**Comment by chinabrant** [comment]
You call the dismiss function more the once. but the remove function should only be call once. So it's crashed. I have fix this.
